spring.application.name=usuarios
spring.datasource.url=jdbc:mysql:
spring.datasource.username=User
spring.datasource.password=Pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081